spring.application.name=climaalertapi
weather.api.key=${WEATHER_API_KEY}
weather.api.url=${WEATHER_API_URL:https://api.weatherapi.com/v1}
sendgrid.api-key=${SENDGRID_API_KEY}
sendgrid.from-email=${SENDGRID_FROM_EMAIL}
schedule.alerta.interval=0 */1 * * * *
schedule.clima.interval=0 */5 * * * *
